### ISSUE TITLE
Nav return key function

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/chatty-scissors#19]
## User story
* As a user, I want to type a message. When I hit enter/return, my message should print to the chatbox
* As a user, when my message has been printed, the text input should be empty.
## Dev notes
* Enter/return key code is 13. Create an if statement waiting for this key code to be entered. Execute printing to chatbox when this is active.
* Take value from text input and print that to the page
* After submission, empty text input and make the box active again.
## Acceptance Criteria
* When I type in the text input, I should be able to submit my text
* When the text is submitted, it is printed to the chatbox
* When the text is submitted, the text input is empty
* When the text is submitted, the text input is active, awaiting more user input

**Comment by morecallan** [comment]
What is the definition of "submitted"; how would someone test this?
