### ISSUE TITLE
Change Theme Buttons/Modal Box

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-8/chatty-scissors#21]
# User Story
User should see a Change Theme Button on the page.  

# Acceptance Criteria
- Remove the existing elements for changing the theme.
- When user click on Change Theme element, show a Bootstrap modal dialog box.

# Tech Notes
- Add a button/link to the UI labeled "Change Theme".
- Add event listener for when the user clicks on the Change Theme Button.
- show a Bootstrap modal dialog box.

**Comment by morecallan** [comment]
Does this ticket include what happens upon clicking on a theme?
