### ISSUE TITLE
Page auto-population/ XHR

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/chatty-scissors#30]
## User story
* I should see some chats when page has been loaded
## Dev notes
* Create XHR request to get Data from JSON
* Pass JSON data into text print function that places messages on page
* Pull users from JSON file and store them in users array
## Acceptance
* Console.log auto populate information
* Console.log users

**Comment by morecallan** [comment]
Let's talk about this after we talk about issue #26
